In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import (confusion_matrix, accuracy_score, precision_score, recall_score, cohen_kappa_score, roc_auc_score, roc_curve, ConfusionMatrixDisplay, classification_report)

In [64]:
df = pd.read_csv('credit_risk_dataset.csv')

In [65]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [66]:
df.shape

(32581, 12)

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB

In [68]:
df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [69]:
df.duplicated().sum()

np.int64(165)

In [70]:
df[df.duplicated()]

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
15975,23,42000,RENT,5.0,VENTURE,B,6000,9.99,0,0.14,N,4
15989,23,90000,MORTGAGE,7.0,EDUCATION,B,8000,10.36,0,0.09,N,3
15995,24,48000,MORTGAGE,4.0,MEDICAL,A,4000,5.42,0,0.08,N,4
16025,24,10000,RENT,8.0,PERSONAL,A,3000,7.90,1,0.30,N,3
16028,23,100000,MORTGAGE,7.0,EDUCATION,A,15000,7.88,0,0.15,N,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32010,42,39996,MORTGAGE,2.0,HOMEIMPROVEMENT,A,2500,5.42,0,0.06,N,12
32047,36,250000,RENT,2.0,DEBTCONSOLIDATION,A,20000,7.88,0,0.08,N,17
32172,49,120000,MORTGAGE,12.0,MEDICAL,B,12000,10.99,0,0.10,N,12
32259,39,40000,OWN,4.0,VENTURE,B,1000,10.37,0,0.03,N,16
32279,43,11340,RENT,4.0,EDUCATION,C,1950,NaN,1,0.17,N,11

In [71]:
df = df.drop_duplicates()

In [72]:
df.duplicated().sum()

np.int64(0)

In [73]:
df[df['person_age'] >= 100]

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
81,144,250000,RENT,4.0,VENTURE,C,4800,13.57,0,0.02,N,3
183,144,200000,MORTGAGE,4.0,EDUCATION,B,6000,11.86,0,0.03,N,2
575,123,80004,RENT,2.0,EDUCATION,B,20400,10.25,0,0.25,N,3
747,123,78000,RENT,7.0,VENTURE,B,20000,NaN,0,0.26,N,4
32297,144,6000000,MORTGAGE,12.0,PERSONAL,C,5000,12.73,0,0.00,N,25

In [74]:
df = df[df['person_age'] <= 100]

In [75]:
df.shape

(32411, 12)

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32411 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32411 non-null  int64
 1   person_income               32411 non-null  int64
 2   person_home_ownership       32411 non-null  object
 3   person_emp_length           31524 non-null  float64
 4   loan_intent                 32411 non-null  object
 5   loan_grade                  32411 non-null  object
 6   loan_amnt                   32411 non-null  int64
 7   loan_int_rate               29317 non-null  float64
 8   loan_status                 32411 non-null  int64
 9   loan_percent_income         32411 non-null  float64
 10  cb_person_default_on_file   32411 non-null  object
 11  cb_person_cred_hist_length  32411 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.2+ MB

In [77]:
df.isna().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              887
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3094
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [78]:
df = df[df['person_emp_length'].isna()|(df['person_emp_length'] <= df['person_age'])]

In [79]:
df.shape

(32409, 12)

In [80]:
df['loan_status'].value_counts() #data is imbalanced data

loan_status
0    25321
1     7088
Name: count, dtype: int64

In [81]:
category1 = 7088/32409

In [82]:
category0 = 25321/32409

In [83]:
category1, category0

(0.2187046807985436, 0.7812953192014563)

In [84]:
le = LabelEncoder()

In [85]:
df['person_home_ownership'] = le.fit_transform(df['person_home_ownership'])
df['loan_grade'] = le.fit_transform(df['loan_grade'])
df['loan_intent'] = le.fit_transform(df['loan_intent'])
df['cb_person_default_on_file'] = le.fit_transform(df['cb_person_default_on_file'])

In [86]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
1,21,9600,2,5.0,1,1,1000,11.14,0,0.10,0,2
2,25,9600,0,1.0,3,2,5500,12.87,1,0.57,0,3
3,23,65500,3,4.0,3,2,35000,15.23,1,0.53,0,2
4,24,54400,3,8.0,3,2,35000,14.27,1,0.55,1,4
5,21,9900,2,2.0,5,0,2500,7.14,1,0.25,0,2

In [87]:
#imputation
imputer = SimpleImputer(strategy = 'median')
df = pd.DataFrame(imputer.fit_transform(df), columns = df.columns, index = df.index)

In [88]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
1,21.0,9600.0,2.0,5.0,1.0,1.0,1000.0,11.14,0.0,0.10,0.0,2.0
2,25.0,9600.0,0.0,1.0,3.0,2.0,5500.0,12.87,1.0,0.57,0.0,3.0
3,23.0,65500.0,3.0,4.0,3.0,2.0,35000.0,15.23,1.0,0.53,0.0,2.0
4,24.0,54400.0,3.0,8.0,3.0,2.0,35000.0,14.27,1.0,0.55,1.0,4.0
5,21.0,9900.0,2.0,2.0,5.0,0.0,2500.0,7.14,1.0,0.25,0.0,2.0

In [89]:
X = df.drop('loan_status', axis = 1)

In [90]:
df['loan_status'].value_counts(normalize = True)

loan_status
0.0    0.781295
1.0    0.218705
Name: proportion, dtype: float64

In [91]:
y = df['loan_status'].astype(int)

In [92]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 60, stratify = y)